package com.fournierMarine.cgi.stage.FoodRescueApp;

import com.fournierMarine.cgi.stage.FoodRescueApp.models.Items;
import com.fournierMarine.cgi.stage.FoodRescueApp.repository.ItemsRepository;
import org.springframework.stereotype.Component;

@Component
public class DatabasePopulator {
    private final ItemsRepository itemsRepository;

    public DatabasePopulator(ItemsRepository itemsRepository) {
        this.itemsRepository = itemsRepository;
    }

    public void populator() {
        itemsRepository.deleteAll();
        itemsRepository.save(new Items("Frango", "Chicken"));
        itemsRepository.save(new Items("Salmão", "Salmon"));
        itemsRepository.save(new Items("Carne bovina", "Beef"));
        itemsRepository.save(new Items("Carne de porco", "Pork"));
        itemsRepository.save(new Items("Abacate", "Avocado"));
        itemsRepository.save(new Items("vinagre de maçã", "Apple Cider Vinegar"));
        itemsRepository.save(new Items("Espargos", "Asparagus"));
        itemsRepository.save(new Items("Beringela", "Aubergine"));
        itemsRepository.save(new Items("Tomates Baby Plum", "Baby Plum Tomatoes"));
        itemsRepository.save(new Items("Bacon", "Bacon"));
        itemsRepository.save(new Items("Fermento em pó", "Baking Powder"));
        itemsRepository.save(new Items("Vinagre balsâmico", "Balsamic Vinegar"));
        itemsRepository.save(new Items("Manjericão", "Basil"));
        itemsRepository.save(new Items("Folhas de manjericão", "Basil Leaves"));
        itemsRepository.save(new Items("Arroz basmati", "Basmati Rice"));
        itemsRepository.save(new Items("folha de louro", "Bay Leaf"));
        itemsRepository.save(new Items("folhas de louro", "Bay Leaves"));
        itemsRepository.save(new Items("Bife de peito", "Beef Brisket"));
        itemsRepository.save(new Items("Filé de bife", "Beef Fillet"));
        itemsRepository.save(new Items("molho de carne", "Beef Gravy"));
        itemsRepository.save(new Items("caldo de carne", "Beef Stock"));
        itemsRepository.save(new Items("Bicarbonato de sódio", "Bicarbonate Of Soda"));
        itemsRepository.save(new Items("Arroz indiano Masala", "Biryani Masala"));
        itemsRepository.save(new Items("Pimenta preta", "Black Pepper"));
        itemsRepository.save(new Items("melaço preto", "Black Treacle"));
        itemsRepository.save(new Items("Feijão Borlotti", "Borlotti Beans"));
        itemsRepository.save(new Items("Macarrão Bowtie", "Bowtie Pasta"));
        itemsRepository.save(new Items("Maçãs Bramley", "Bramley Apples"));
        itemsRepository.save(new Items("conhaque", "Brandy"));
        itemsRepository.save(new Items("Pão", "Bread"));
        itemsRepository.save(new Items("Migalhas de pão", "Breadcrumbs"));
        itemsRepository.save(new Items("Brócolis", "Broccoli"));
        itemsRepository.save(new Items("Lentilhas Marrons", "Brown Lentils"));
        itemsRepository.save(new Items("Arroz castanho", "Brown Rice"));
        itemsRepository.save(new Items("Açúcar mascavo", "Brown Sugar"));
        itemsRepository.save(new Items("Manteiga", "Butter"));
        itemsRepository.save(new Items("Cacau", "Cacao"));
        itemsRepository.save(new Items("cajun", "Cajun"));
        itemsRepository.save(new Items("Conservas De Tomate", "Canned Tomatoes"));
        itemsRepository.save(new Items("Feijão Cannellini", "Cannellini Beans"));
        itemsRepository.save(new Items("Cardamomo", "Cardamom"));
        itemsRepository.save(new Items("Cenouras", "Carrots"));
        itemsRepository.save(new Items("castanha de caju", "Cashew Nuts"));
        itemsRepository.save(new Items("Castanha de caju", "Cashews"));
        itemsRepository.save(new Items("Açucar refinado", "Caster Sugar"));
        itemsRepository.save(new Items("Pimenta-caiena", "Cayenne Pepper"));
        itemsRepository.save(new Items("Aipo-rábano", "Celeriac"));
        itemsRepository.save(new Items("Salsão", "Celery"));
        itemsRepository.save(new Items("sal de aipo", "Celery Salt"));
        itemsRepository.save(new Items("chalotas", "Challots"));
        itemsRepository.save(new Items("Batata Charlotte", "Charlotte Potatoes"));
        itemsRepository.save(new Items("Queijo cheddar", "Cheddar Cheese"));
        itemsRepository.save(new Items("Queijo", "Cheese"));
        itemsRepository.save(new Items("Queijo Coalho", "Cheese Curds"));
        itemsRepository.save(new Items("Tomate Cherry", "Cherry Tomatoes"));
        itemsRepository.save(new Items("Cogumelo Castanha", "Chestnut Mushroom"));
        itemsRepository.save(new Items("peito de frango", "Chicken Breast"));
        itemsRepository.save(new Items("peito de frango", "Chicken Breasts"));
        itemsRepository.save(new Items("Pernas de galinha", "Chicken Legs"));
        itemsRepository.save(new Items("Caldo de galinha", "Chicken Stock"));
        itemsRepository.save(new Items("Coxa de frango", "Chicken Thighs"));
        itemsRepository.save(new Items("Grão de bico", "Chickpeas"));
        itemsRepository.save(new Items("Pimenta em pó", "Chili Powder"));
        itemsRepository.save(new Items("Manteiga gelada", "Chilled Butter"));
        itemsRepository.save(new Items("Pimenta", "Chilli"));
        itemsRepository.save(new Items("Pimenta em pó", "Chilli Powder"));
        itemsRepository.save(new Items("Brócolis chinês", "Chinese Broccoli"));
        itemsRepository.save(new Items("Pepitas De Chocolate", "Chocolate Chips"));
        itemsRepository.save(new Items("Cebola picada", "Chopped Onion"));
        itemsRepository.save(new Items("Salsa picada", "Chopped Parsley"));
        itemsRepository.save(new Items("tomate picado", "Chopped Tomatoes"));
        itemsRepository.save(new Items("chouriço", "Chorizo"));
        itemsRepository.save(new Items("Pudim de Natal", "Christmas Pudding"));
        itemsRepository.save(new Items("Coentro", "Cilantro"));
        itemsRepository.save(new Items("Canela", "Cinnamon"));
        itemsRepository.save(new Items("Pau de canela", "Cinnamon Stick"));
        itemsRepository.save(new Items("cravo", "Cloves"));
        itemsRepository.save(new Items("açúcar de coco", "Coco Sugar"));
        itemsRepository.save(new Items("Cacau", "Cocoa"));
        itemsRepository.save(new Items("Creme de coco", "Coconut Cream"));
        itemsRepository.save(new Items("Leite de côco", "Coconut Milk"));
        itemsRepository.save(new Items("Queijo Colby Jack", "Colby Jack Cheese"));
        itemsRepository.save(new Items("Água fria", "Cold Water"));
        itemsRepository.save(new Items("Leite condensado", "Condensed Milk"));
        itemsRepository.save(new Items("Coentro", "Coriander"));
        itemsRepository.save(new Items("Folhas de coentro", "Coriander Leaves"));
        itemsRepository.save(new Items("sementes de coentro", "Coriander Seeds"));
        itemsRepository.save(new Items("Tortilhas de milho", "Corn Tortillas"));
        itemsRepository.save(new Items("amido de milho", "Cornstarch"));
        itemsRepository.save(new Items("Creme", "Cream"));
        itemsRepository.save(new Items("cremes frescos", "Creme Fraiche"));
        itemsRepository.save(new Items("Queijo Feta em Cubos", "Cubed Feta Cheese"));
        itemsRepository.save(new Items("Pepino", "Cucumber"));
        itemsRepository.save(new Items("Cominho", "Cumin"));
        itemsRepository.save(new Items("Sementes de cominho", "Cumin Seeds"));
        itemsRepository.save(new Items("caril em pó", "Curry Powder"));
        itemsRepository.save(new Items("Açúcar mascavo", "Dark Brown Sugar"));
        itemsRepository.save(new Items("Açúcar Mascavo Escuro Suave", "Dark Soft Brown Sugar"));
        itemsRepository.save(new Items("Escuro, eu sou Willow", "Dark Soy Sauce"));
        itemsRepository.save(new Items("Açúcar demerara", "Demerara Sugar"));
        itemsRepository.save(new Items("Tomate picados", "Diced Tomatoes"));
        itemsRepository.save(new Items("Biscoitos Digestivos", "Digestive Biscuits"));
        itemsRepository.save(new Items("aneto", "Dill"));
        itemsRepository.save(new Items("Doner Carne", "Doner Meat"));
        itemsRepository.save(new Items("Creme duplo", "Double Cream"));
        itemsRepository.save(new Items("Orégano seco", "Dried Oregano"));
        itemsRepository.save(new Items("Vinho branco seco", "Dry White Wine"));
        itemsRepository.save(new Items("Beringelas", "Egg Plants"));
        itemsRepository.save(new Items("Rolinho de Ovo", "Egg Rolls"));
        itemsRepository.save(new Items("Clara de ovo", "Egg White"));
        itemsRepository.save(new Items("Gemas de ovo", "Egg Yolks"));
        itemsRepository.save(new Items("Ovos", "Eggs"));
        itemsRepository.save(new Items("Molhe de Enchilada", "Enchilada Sauce"));
        itemsRepository.save(new Items("Mostarda Inglesa", "English Mustard"));
        itemsRepository.save(new Items("Azeite Extra Virgem", "Extra Virgin Olive Oil"));
        itemsRepository.save(new Items("Tempero Fajita", "Fajita Seasoning"));
        itemsRepository.save(new Items("borboletas", "Farfalle"));
        itemsRepository.save(new Items("bulbo de funcho", "Fennel Bulb"));
        itemsRepository.save(new Items("sementes de funcho", "Fennel Seeds"));
        itemsRepository.save(new Items("fenacho", "Fenugreek"));
        itemsRepository.save(new Items("queijo feta", "Feta"));
        itemsRepository.save(new Items("Molho de peixe", "Fish Sauce"));
        itemsRepository.save(new Items("Amêndoas em flocos", "Flaked Almonds"));
        itemsRepository.save(new Items("Ovos de Linhaça", "Flax Eggs"));
        itemsRepository.save(new Items("Farinha", "Flour"));
        itemsRepository.save(new Items("Tortilla de farinha", "Flour Tortilla"));
        itemsRepository.save(new Items("Batata Farinha", "Floury Potatoes"));
        itemsRepository.save(new Items("Ovo caipira, batido", "Free-range Egg, Beaten"));
        itemsRepository.save(new Items("Ovos caipiras, batidos", "Free-range Eggs, Beaten"));
        itemsRepository.save(new Items("lentilhas francesas", "French Lentils"));
        itemsRepository.save(new Items("Manjericão fresco", "Fresh Basil"));
        itemsRepository.save(new Items("tomilho fresco", "Fresh Thyme"));
        itemsRepository.save(new Items("Salsa fresca picada", "Freshly Chopped Parsley"));
        itemsRepository.save(new Items("Fritas", "Fries"));
        itemsRepository.save(new Items("Iogurte Gordo", "Full Fat Yogurt"));
        itemsRepository.save(new Items("Garam Masala", "Garam Masala"));
        itemsRepository.save(new Items("Alho", "Garlic"));
        itemsRepository.save(new Items("Dente de alho", "Garlic Clove"));
        itemsRepository.save(new Items("Pó de alho", "Garlic Powder"));
        itemsRepository.save(new Items("Molho de alho", "Garlic Sauce"));
        itemsRepository.save(new Items("Manteiga clarificada", "Ghee"));
        itemsRepository.save(new Items("Ruivo", "Ginger"));
        itemsRepository.save(new Items("Gengibre Cordial", "Ginger Cordial"));
        itemsRepository.save(new Items("pasta de alho e gengibre", "Ginger Garlic Paste"));
        itemsRepository.save(new Items("pasta de gengibre", "Ginger Paste"));
        itemsRepository.save(new Items("Xarope Dourado", "Golden Syrup"));
        itemsRepository.save(new Items("Queijo Gouda", "Gouda Cheese"));
        itemsRepository.save(new Items("Açúcar granulado", "Granulated Sugar"));
        itemsRepository.save(new Items("tomate uva", "Grape Tomatoes"));
        itemsRepository.save(new Items("Iogurte grego", "Greek Yogurt"));
        itemsRepository.save(new Items("Vagens", "Green Beans"));
        itemsRepository.save(new Items("Pimentão verde", "Green Chilli"));
        itemsRepository.save(new Items("Azeitonas verdes", "Green Olives"));
        itemsRepository.save(new Items("Lentilhas Verdes Vermelhas", "Green Red Lentils"));
        itemsRepository.save(new Items("salsa verde", "Green Salsa"));
        itemsRepository.save(new Items("Amêndoas moídas", "Ground Almonds"));
        itemsRepository.save(new Items("Cominho em pó", "Ground Cumin"));
        itemsRepository.save(new Items("gengibre moído", "Ground Ginger"));
        itemsRepository.save(new Items("Gruyère", "Gruyère"));
        itemsRepository.save(new Items("Cascas duras de taco", "Hard Taco Shells"));
        itemsRepository.save(new Items("Especiaria Harissa", "Harissa Spice"));
        itemsRepository.save(new Items("Creme de leite", "Heavy Cream"));
        itemsRepository.save(new Items("Mel", "Honey"));
        itemsRepository.save(new Items("raiz-forte", "Horseradish"));
        itemsRepository.save(new Items("Caldo de Carne Quente", "Hot Beef Stock"));
        itemsRepository.save(new Items("Molho picante", "Hotsauce"));
        itemsRepository.save(new Items("Sorvete", "Ice Cream"));
        itemsRepository.save(new Items("Linguiças Italianas de Funcho", "Italian Fennel Sausages"));
        itemsRepository.save(new Items("tempero italiano", "Italian Seasoning"));
        itemsRepository.save(new Items("Pimenta jalapeno", "Jalapeno"));
        itemsRepository.save(new Items("Arroz de jasmim", "Jasmine Rice"));
        itemsRepository.save(new Items("Alcachofras de Jerusalém", "Jerusalem Artichokes"));
        itemsRepository.save(new Items("Couve", "Kale"));
        itemsRepository.save(new Items("Khus Khus", "Khus Khus"));
        itemsRepository.save(new Items("Camarão rei", "King Prawns"));
        itemsRepository.save(new Items("Sal Kosher", "Kosher Salt"));
        itemsRepository.save(new Items("Cordeiro", "Lamb"));
        itemsRepository.save(new Items("Costeletas de cordeiro lombo", "Lamb Loin Chops"));
        itemsRepository.save(new Items("carne moída", "Lamb Mince"));
        itemsRepository.save(new Items("Folhas de Lasanha", "Lasagne Sheets"));
        itemsRepository.save(new Items("Carne moída magra", "Lean Minced Beef"));
        itemsRepository.save(new Items("alho-poró", "Leek"));
        itemsRepository.save(new Items("Limão", "Lemon"));
        itemsRepository.save(new Items("Suco de limão", "Lemon Juice"));
        itemsRepository.save(new Items("raspas de limão", "Lemon Zest"));
        itemsRepository.save(new Items("limões", "Lemons"));
        itemsRepository.save(new Items("Alface", "Lettuce"));
        itemsRepository.save(new Items("Lima", "Lime"));
        itemsRepository.save(new Items("Alface Joia", "Little Gem Lettuce"));
        itemsRepository.save(new Items("Macarrão", "Macaroni"));
        itemsRepository.save(new Items("Cavalinha", "Mackerel"));
        itemsRepository.save(new Items("Pasta Madras", "Madras Paste"));
        itemsRepository.save(new Items("Manjerona", "Marjoram"));
        itemsRepository.save(new Items("Massaman Curry Paste", "Massaman Curry Paste"));
        itemsRepository.save(new Items("Tâmaras Medjool", "Medjool Dates"));
        itemsRepository.save(new Items("ninhos de merengue", "Meringue Nests"));
        itemsRepository.save(new Items("Leite", "Milk"));
        itemsRepository.save(new Items("Alho picado", "Minced Garlic"));
        itemsRepository.save(new Items("marshmallows em miniatura", "Miniature Marshmallows"));
        itemsRepository.save(new Items("hortelã", "Mint"));
        itemsRepository.save(new Items("Queijo Monterey Jack", "Monterey Jack Cheese"));
        itemsRepository.save(new Items("bolas de Mozzarella", "Mozzarella Balls"));
        itemsRepository.save(new Items("Açúcar mascavado", "Muscovado Sugar"));
        itemsRepository.save(new Items("cogumelos", "Mushrooms"));
        itemsRepository.save(new Items("Mostarda", "Mustard"));
        itemsRepository.save(new Items("mostarda em pó", "Mustard Powder"));
        itemsRepository.save(new Items("sementes de mostarda", "Mustard Seeds"));
        itemsRepository.save(new Items("noz-moscada", "Nutmeg"));
        itemsRepository.save(new Items("Óleo", "Oil"));
        itemsRepository.save(new Items("Azeite", "Olive Oil"));
        itemsRepository.save(new Items("Cebola Sal", "Onion Salt"));
        itemsRepository.save(new Items("cebola", "Onions"));
        itemsRepository.save(new Items("Laranja", "Orange"));
        itemsRepository.save(new Items("Raspas de laranja", "Orange Zest"));
        itemsRepository.save(new Items("Orégano", "Oregano"));
        itemsRepository.save(new Items("Molho de ostras", "Oyster Sauce"));
        itemsRepository.save(new Items("páprica", "Paprika"));
        itemsRepository.save(new Items("parmaham", "Parma Ham"));
        itemsRepository.save(new Items("parmesão", "Parmesan"));
        itemsRepository.save(new Items("Queijo parmesão", "Parmesan Cheese"));
        itemsRepository.save(new Items("Queijo parmesão", "Parmigiano-reggiano"));
        itemsRepository.save(new Items("Salsinha", "Parsley"));
        itemsRepository.save(new Items("Manteiga de amendoim", "Peanut Butter"));
        itemsRepository.save(new Items("Óleo de amendoim", "Peanut Oil"));
        itemsRepository.save(new Items("amendoim", "Peanuts"));
        itemsRepository.save(new Items("Ervilhas", "Peas"));
        itemsRepository.save(new Items("pecorino", "Pecorino"));
        itemsRepository.save(new Items("Macarrão Penne", "Penne Rigate"));
        itemsRepository.save(new Items("Pimenta", "Pepper"));
        itemsRepository.save(new Items("Pinhões", "Pine Nuts"));
        itemsRepository.save(new Items("Azeitonas pretas sem caroço", "Pitted Black Olives"));
        itemsRepository.save(new Items("Chocolate Simples", "Plain Chocolate"));
        itemsRepository.save(new Items("farinha de trigo", "Plain Flour"));
        itemsRepository.save(new Items("tomate ameixa", "Plum Tomatoes"));
        itemsRepository.save(new Items("fécula de batata", "Potato Starch"));
        itemsRepository.save(new Items("Batatas", "Potatoes"));
        itemsRepository.save(new Items("camarão", "Prawns"));
        itemsRepository.save(new Items("massa folhada", "Puff Pastry"));
        itemsRepository.save(new Items("Geleia de framboesa", "Raspberry Jam"));
        itemsRepository.save(new Items("Camarão Real Cru", "Raw King Prawns"));
        itemsRepository.save(new Items("Flocos de Chile Vermelho", "Red Chile Flakes"));
        itemsRepository.save(new Items("pimentão vermelho", "Red Chilli"));
        itemsRepository.save(new Items("pimenta vermelha em pó", "Red Chilli Powder"));
        itemsRepository.save(new Items("Cebolas vermelhas", "Red Onions"));
        itemsRepository.save(new Items("Pimentão vermelho", "Red Pepper"));
        itemsRepository.save(new Items("Flocos de pimenta vermelha", "Red Pepper Flakes"));
        itemsRepository.save(new Items("Vinho tinto", "Red Wine"));
        itemsRepository.save(new Items("Feijão Refogado", "Refried Beans"));
        itemsRepository.save(new Items("Arroz", "Rice"));
        itemsRepository.save(new Items("Macarrão de arroz", "Rice Noodles"));
        itemsRepository.save(new Items("macarrão de arroz", "Rice Stick Noodles"));
        itemsRepository.save(new Items("Arroz Vermicelli", "Rice Vermicelli"));
        itemsRepository.save(new Items("rigatoni", "Rigatoni"));
        itemsRepository.save(new Items("Foguete", "Rocket"));
        itemsRepository.save(new Items("aveia em flocos", "Rolled Oats"));
        itemsRepository.save(new Items("Açafrão", "Saffron"));
        itemsRepository.save(new Items("Sábio", "Sage"));
        itemsRepository.save(new Items("Interesse", "Sake"));
        itemsRepository.save(new Items("salsa", "Salsa"));
        itemsRepository.save(new Items("Sal", "Salt"));
        itemsRepository.save(new Items("Manteiga salgada", "Salted Butter"));
        itemsRepository.save(new Items("Salsichas", "Sausages"));
        itemsRepository.save(new Items("Sal marinho", "Sea Salt"));
        itemsRepository.save(new Items("Farinha de trigo com fermento", "Self-raising Flour"));
        itemsRepository.save(new Items("Leite semidesnatado", "Semi-skimmed Milk"));
        itemsRepository.save(new Items("semente de gergelim", "Sesame Seed"));
        itemsRepository.save(new Items("chalotas", "Shallots"));
        itemsRepository.save(new Items("queijo mexicano ralado", "Shredded Mexican Cheese"));
        itemsRepository.save(new Items("Queijo Monterey Jack Ralado", "Shredded Monterey Jack Cheese"));
        itemsRepository.save(new Items("Batatas pequenas", "Small Potatoes"));
        itemsRepository.save(new Items("Páprica defumada", "Smoked Paprika"));
        itemsRepository.save(new Items("páprica defumada", "Smoky Paprika"));
        itemsRepository.save(new Items("Nata", "Sour Cream"));
        itemsRepository.save(new Items("eu sou salgueiro", "Soy Sauce"));
        itemsRepository.save(new Items("Leite de soja", "Soya Milk"));
        itemsRepository.save(new Items("Espaguete", "Spaghetti"));
        itemsRepository.save(new Items("Espinafre", "Spinach"));
        itemsRepository.save(new Items("Cebolinhas", "Spring Onions"));
        itemsRepository.save(new Items("Abóbora", "Squash"));
        itemsRepository.save(new Items("Legumes salteados", "Stir-fry Vegetables"));
        itemsRepository.save(new Items("morangos", "Strawberries"));
        itemsRepository.save(new Items("Açúcar", "Sugar"));
        itemsRepository.save(new Items("Sultanas", "Sultanas"));
        itemsRepository.save(new Items("Óleo de girassol", "Sunflower Oil"));
        itemsRepository.save(new Items("bola de tamarindo", "Tamarind Ball"));
        itemsRepository.save(new Items("Pasta de tamarindo", "Tamarind Paste"));
        itemsRepository.save(new Items("Molho de peixe tailandês", "Thai Fish Sauce"));
        itemsRepository.save(new Items("Pasta de curry verde tailandesa", "Thai Green Curry Paste"));
        itemsRepository.save(new Items("Massa de Caril Vermelho Tailandês", "Thai Red Curry Paste"));
        itemsRepository.save(new Items("Tomilho", "Thyme"));
        itemsRepository.save(new Items("Tomato Ketchup", "Tomato Ketchup"));
        itemsRepository.save(new Items("Tomato Puree", "Tomato Puree"));
        itemsRepository.save(new Items("Tomates", "Tomatoes"));
        itemsRepository.save(new Items("Lentilha amarela", "Toor Dal"));
        itemsRepository.save(new Items("Atum", "Tuna"));
        itemsRepository.save(new Items("Cúrcuma", "Turmeric"));
        itemsRepository.save(new Items("açafrão em pó", "Turmeric Powder"));
        itemsRepository.save(new Items("Nabos", "Turnips"));
        itemsRepository.save(new Items("Baunilha", "Vanilla"));
        itemsRepository.save(new Items("Extrato de baunilha", "Vanilla Extract"));
        itemsRepository.save(new Items("Vitela", "Veal"));
        itemsRepository.save(new Items("Manteiga vegana", "Vegan Butter"));
        itemsRepository.save(new Items("Óleo vegetal", "Vegetable Oil"));
        itemsRepository.save(new Items("Caldo de Legumes", "Vegetable Stock"));
        itemsRepository.save(new Items("Cubo de Caldo de Legumes", "Vegetable Stock Cube"));
        itemsRepository.save(new Items("molho vinagrete", "Vinaigrette Dressing"));
        itemsRepository.save(new Items("folhas de videira", "Vine Leaves"));
        itemsRepository.save(new Items("Vinagre", "Vinegar"));
        itemsRepository.save(new Items("Água", "Water"));
        itemsRepository.save(new Items("Pepitas De Chocolate Branco", "White Chocolate Chips"));
        itemsRepository.save(new Items("peixe branco", "White Fish"));
        itemsRepository.save(new Items("Filetes de Peixe Branco", "White Fish Fillets"));
        itemsRepository.save(new Items("Vinagre branco", "White Vinegar"));
        itemsRepository.save(new Items("Vinho branco", "White Wine"));
        itemsRepository.save(new Items("Leite inteiro", "Whole Milk"));
        itemsRepository.save(new Items("Trigo", "Whole Wheat"));
        itemsRepository.save(new Items("Pão integral", "Wholegrain Bread"));
        itemsRepository.save(new Items("Molho Worcestershire", "Worcestershire Sauce"));
        itemsRepository.save(new Items("Iogurte", "Yogurt"));
        itemsRepository.save(new Items("Abobrinha", "Zucchini"));
        itemsRepository.save(new Items("salgadinhos", "Pretzels"));
        itemsRepository.save(new Items("Requeijão cremoso", "Cream Cheese"));
        itemsRepository.save(new Items("Açucar em pó", "Icing Sugar"));
        itemsRepository.save(new Items("pipoca de caramelo", "Toffee Popcorn"));
        itemsRepository.save(new Items("Caramelo", "Caramel"));
        itemsRepository.save(new Items("calda de caramelo", "Caramel Sauce"));
        itemsRepository.save(new Items("Macarrão", "Tagliatelle"));
        itemsRepository.save(new Items("Fettuccine", "Fettuccine"));
        itemsRepository.save(new Items("Creme coalhado", "Clotted Cream"));
        itemsRepository.save(new Items("Farinha de milho", "Corn Flour"));
        itemsRepository.save(new Items("Mexilhões", "Mussels"));
        itemsRepository.save(new Items("Vídeo", "Fideo"));
        itemsRepository.save(new Items("Tamboril", "Monkfish"));
        itemsRepository.save(new Items("Macarrão Vermicelli", "Vermicelli Pasta"));
        itemsRepository.save(new Items("lula bebê", "Baby Squid"));
        itemsRepository.save(new Items("Lula", "Squid"));
        itemsRepository.save(new Items("Estoque de Peixes", "Fish Stock"));
        itemsRepository.save(new Items("sardinhas", "Pilchards"));
        itemsRepository.save(new Items("Azeitonas pretas", "Black Olives"));
        itemsRepository.save(new Items("Cebola", "Onion"));
        itemsRepository.save(new Items("Tomate", "Tomato"));
        itemsRepository.save(new Items("Pato", "Duck"));
        itemsRepository.save(new Items("pernas de pato", "Duck Legs"));
        itemsRepository.save(new Items("cubo de caldo de galinha", "Chicken Stock Cube"));
        itemsRepository.save(new Items("Macarrão Pappardelle", "Pappardelle Pasta"));
        itemsRepository.save(new Items("Macarrão Paccheri", "Paccheri Pasta"));
        itemsRepository.save(new Items("Macarrão Linguine", "Linguine Pasta"));
        itemsRepository.save(new Items("Ervilhas Açucaradas", "Sugar Snap Peas"));
        itemsRepository.save(new Items("Pão duro", "Crusty Bread"));
        itemsRepository.save(new Items("Requeijão cremoso", "Fromage Frais"));
        itemsRepository.save(new Items("Amêijoas", "Clams"));
        itemsRepository.save(new Items("Passado", "Passata"));
        itemsRepository.save(new Items("óleo de colza", "Rapeseed Oil"));
        itemsRepository.save(new Items("Queijo Stilton", "Stilton Cheese"));
        itemsRepository.save(new Items("Perna de cordeiro", "Lamb Leg"));
        itemsRepository.save(new Items("Ombro de carneiro", "Lamb Shoulder"));
        itemsRepository.save(new Items("Damasco", "Apricot"));
        itemsRepository.save(new Items("Abóbora", "Butternut Squash"));
        itemsRepository.save(new Items("cuscuz", "Couscous"));
        itemsRepository.save(new Items("Carne moída", "Minced Beef"));
        itemsRepository.save(new Items("peru picado", "Turkey Mince"));
        itemsRepository.save(new Items("Molho de churrasco", "Barbeque Sauce"));
        itemsRepository.save(new Items("Milho doce", "Sweetcorn"));
        itemsRepository.save(new Items("gordura de ganso", "Goose Fat"));
        itemsRepository.save(new Items("gordura de pato", "Duck Fat"));
        itemsRepository.save(new Items("Funcho", "Fennel"));
        itemsRepository.save(new Items("Vinagre de vinho tinto", "Red Wine Vinegar"));
        itemsRepository.save(new Items("Feijão branco", "Haricot Beans"));
        itemsRepository.save(new Items("Alecrim", "Rosemary"));
        itemsRepository.save(new Items("Feijões de manteiga", "Butter Beans"));
        itemsRepository.save(new Items("Feijão carioca", "Pinto Beans"));
        itemsRepository.save(new Items("Molho de tomate", "Tomato Sauce"));
        itemsRepository.save(new Items("Mascarpone", "Mascarpone"));
        itemsRepository.save(new Items("Mussarela", "Mozzarella"));
        itemsRepository.save(new Items("ricota", "Ricotta"));
        itemsRepository.save(new Items("Damascos secos", "Dried Apricots"));
        itemsRepository.save(new Items("alcaparras", "Capers"));
        itemsRepository.save(new Items("Banana", "Banana"));
        itemsRepository.save(new Items("Framboesas", "Raspberries"));
        itemsRepository.save(new Items("Amoras", "Blueberries"));
        itemsRepository.save(new Items("nozes", "Walnuts"));
        itemsRepository.save(new Items("Nozes Pecan", "Pecan Nuts"));
        itemsRepository.save(new Items("Xarope de bordo", "Maple Syrup"));
        itemsRepository.save(new Items("Açúcar Mascavo Claro", "Light Brown Soft Sugar"));
        itemsRepository.save(new Items("Açúcar Mascavo Escuro", "Dark Brown Soft Sugar"));
        itemsRepository.save(new Items("Lascas de Chocolate Amargo", "Dark Chocolate Chips"));
        itemsRepository.save(new Items("Chocolate ao Leite", "Milk Chocolate"));
        itemsRepository.save(new Items("Chocolate escuro", "Dark Chocolate"));
        itemsRepository.save(new Items("Abóbora", "Pumpkin"));
        itemsRepository.save(new Items("massa quebrada", "Shortcrust Pastry"));
        itemsRepository.save(new Items("biscoitos de amendoim", "Peanut Cookies"));
        itemsRepository.save(new Items("folhas de gelatina", "Gelatine Leafs"));
        itemsRepository.save(new Items("Pé-de-moleque", "Peanut Brittle"));
        itemsRepository.save(new Items("Pêssegos", "Peaches"));
        itemsRepository.save(new Items("Pimenta amarela", "Yellow Pepper"));
        itemsRepository.save(new Items("Pimenta verde", "Green Pepper"));
        itemsRepository.save(new Items("abobrinhas", "Courgettes"));
        itemsRepository.save(new Items("tomate enlatado", "Tinned Tomatos"));
        itemsRepository.save(new Items("Castanhas", "Chestnuts"));
        itemsRepository.save(new Items("Cogumelos selvagens", "Wild Mushrooms"));
        itemsRepository.save(new Items("Óleo de trufa", "Truffle Oil"));
        itemsRepository.save(new Items("paneer", "Paneer"));
        itemsRepository.save(new Items("Pão naan", "Naan Bread"));
        itemsRepository.save(new Items("lentilhas", "Lentils"));
        itemsRepository.save(new Items("Vegetais assados", "Roasted Vegetables"));
        itemsRepository.save(new Items("Feijão", "Kidney Beans"));
        itemsRepository.save(new Items("Grãos mistos", "Mixed Grain"));
        itemsRepository.save(new Items("tahini", "Tahini"));
        itemsRepository.save(new Items("Tortas", "Tortillas"));
        itemsRepository.save(new Items("Macarrão Udon", "Udon Noodles"));
        itemsRepository.save(new Items("Repolho", "Cabbage"));
        itemsRepository.save(new Items("Cogumelos shitake", "Shiitake Mushrooms"));
        itemsRepository.save(new Items("Mirin", "Mirin"));
        itemsRepository.save(new Items("óleo de gergelim", "Sesame Seed Oil"));
        itemsRepository.save(new Items("baguete", "Baguette"));
        itemsRepository.save(new Items("tomates de videira", "Vine Tomatoes"));
        itemsRepository.save(new Items("Sebo", "Suet"));
        itemsRepository.save(new Items("sueco", "Swede"));
        itemsRepository.save(new Items("presunto", "Ham"));
        itemsRepository.save(new Items("Ostras", "Oysters"));
        itemsRepository.save(new Items("cerveja preta", "Stout"));
        itemsRepository.save(new Items("banha", "Lard"));
        itemsRepository.save(new Items("rim de cordeiro", "Lamb Kidney"));
        itemsRepository.save(new Items("Rim de Boi", "Beef Kidney"));
        itemsRepository.save(new Items("arinca", "Haddock"));
        itemsRepository.save(new Items("Haddock Defumado", "Smoked Haddock"));
        itemsRepository.save(new Items("Couve de Bruxelas", "Brussels Sprouts"));
        itemsRepository.save(new Items("Passas de uva", "Raisins"));
        itemsRepository.save(new Items("Groselhas", "Currants"));
        itemsRepository.save(new Items("Quindim", "Custard"));
        itemsRepository.save(new Items("Peeling Misto", "Mixed Peel"));
        itemsRepository.save(new Items("Groselha", "Redcurrants"));
        itemsRepository.save(new Items("Amora silvestre", "Blackberries"));
        itemsRepository.save(new Items("Avelãs", "Hazlenuts"));
        itemsRepository.save(new Items("Maçã Braeburn", "Braeburn Apples"));
        itemsRepository.save(new Items("Corante Alimentar Vermelho", "Red Food Colouring"));
        itemsRepository.save(new Items("Corante Alimentar Rosa", "Pink Food Colouring"));
        itemsRepository.save(new Items("Corante Alimentar Azul", "Blue Food Colouring"));
        itemsRepository.save(new Items("Corante Alimentar Amarelo", "Yellow Food Colouring"));
        itemsRepository.save(new Items("Geléia de damasco", "Apricot Jam"));
        itemsRepository.save(new Items("Marzipan", "Marzipan"));
        itemsRepository.save(new Items("Amêndoas", "Almonds"));
        itemsRepository.save(new Items("pudim preto", "Black Pudding"));
        itemsRepository.save(new Items("Feijao cozido", "Baked Beans"));
        itemsRepository.save(new Items("Farinha branca", "White Flour"));
        itemsRepository.save(new Items("Levedura", "Yeast"));
        itemsRepository.save(new Items("Mix de frutas", "Fruit Mix"));
        itemsRepository.save(new Items("Fruta seca", "Dried Fruit"));
        itemsRepository.save(new Items("Cereja", "Cherry"));
        itemsRepository.save(new Items("Glace Cherry", "Glace Cherry"));
        itemsRepository.save(new Items("melaço", "Treacle"));
        itemsRepository.save(new Items("Aveia", "Oatmeal"));
        itemsRepository.save(new Items("Aveia", "Oats"));
        itemsRepository.save(new Items("Ovo", "Egg"));
        itemsRepository.save(new Items("Canela Bovina", "Beef Shin"));
        itemsRepository.save(new Items("bouquet garni", "Bouquet Garni"));
        itemsRepository.save(new Items("Creme Simples", "Single Cream"));
        itemsRepository.save(new Items("geléia de vinho tinto", "Red Wine Jelly"));
        itemsRepository.save(new Items("Maçãs", "Apples"));
        itemsRepository.save(new Items("Queijo de cabra", "Goats Cheese"));
        itemsRepository.save(new Items("Prosciutto", "Prosciutto"));
        itemsRepository.save(new Items("Manteiga Sem Sal", "Unsalted Butter"));
        itemsRepository.save(new Items("brie", "Brie"));
        itemsRepository.save(new Items("Folhas de Estragão", "Tarragon Leaves"));
        itemsRepository.save(new Items("Cebolinha", "Chives"));
        itemsRepository.save(new Items("peras", "Pears"));
        itemsRepository.save(new Items("Chocolate Branco", "White Chocolate"));
        itemsRepository.save(new Items("Anis estrelado", "Star Anise"));
        itemsRepository.save(new Items("Camarão tigre", "Tiger Prawns"));
        itemsRepository.save(new Items("Creme em Pó", "Custard Powder"));
        itemsRepository.save(new Items("Côco seco", "Desiccated Coconut"));
        itemsRepository.save(new Items("Ervilhas congeladas", "Frozen Peas"));
        itemsRepository.save(new Items("carne de porco picada", "Minced Pork"));
        itemsRepository.save(new Items("creme de milho", "Creamed Corn"));
        itemsRepository.save(new Items("Tomates secos", "Sun-Dried Tomatoes"));
        itemsRepository.save(new Items("Mostarda Dijon", "Dijon Mustard"));
        itemsRepository.save(new Items("Molho Tabasco", "Tabasco Sauce"));
        itemsRepository.save(new Items("Óleo de canola", "Canola Oil"));
        itemsRepository.save(new Items("Bacalhau", "Cod"));
        itemsRepository.save(new Items("bacalhau", "Salt Cod"));
        itemsRepository.save(new Items("Ackee", "Ackee"));
        itemsRepository.save(new Items("Idiota", "Jerk"));
        itemsRepository.save(new Items("Carne moída", "Ground Beef"));
        itemsRepository.save(new Items("berinjela baby", "Baby Aubergine"));
        itemsRepository.save(new Items("Paelha de Arroz", "Paella Rice"));
        itemsRepository.save(new Items("capô escocês", "Scotch Bonnet"));
        itemsRepository.save(new Items("Rabo de boi", "Oxtail"));
        itemsRepository.save(new Items("Favas", "Broad Beans"));
        itemsRepository.save(new Items("Cioba", "Red Snapper"));
        itemsRepository.save(new Items("vinagre de malte", "Malt Vinegar"));
        itemsRepository.save(new Items("Vinagre de arroz", "Rice Vinegar"));
        itemsRepository.save(new Items("Castanha D'água", "Water Chestnut"));
        itemsRepository.save(new Items("tofu", "Tofu"));
        itemsRepository.save(new Items("Doubanjiang", "Doubanjiang"));
        itemsRepository.save(new Items("Feijão Preto Fermentado", "Fermented Black Beans"));
        itemsRepository.save(new Items("Cebolinha", "Scallions"));
        itemsRepository.save(new Items("Pimenta de Sichuan", "Sichuan Pepper"));
        itemsRepository.save(new Items("Pele Wonton", "Wonton Skin"));
        itemsRepository.save(new Items("Amido", "Starch"));
        itemsRepository.save(new Items("Vinho de arroz", "Rice wine"));
        itemsRepository.save(new Items("Cozinhando vinho", "Cooking wine"));
        itemsRepository.save(new Items("Molho de pato", "Duck Sauce"));
        itemsRepository.save(new Items("Gochujang", "Gochujang"));
        itemsRepository.save(new Items("Broto de feijão", "Bean Sprouts"));
        itemsRepository.save(new Items("Macarrão", "Noodles"));
        itemsRepository.save(new Items("Cogumelos orelha-de-pau", "Wood Ear Mushrooms"));
        itemsRepository.save(new Items("rum escuro", "Dark Rum"));
        itemsRepository.save(new Items("Rum claro", "Light Rum"));
        itemsRepository.save(new Items("Rum", "Rum"));
        itemsRepository.save(new Items("bolinhos ingleses", "English Muffins"));
        itemsRepository.save(new Items("bolos", "Muffins"));
        itemsRepository.save(new Items("Vinagre de vinho branco", "White Wine Vinegar"));
        itemsRepository.save(new Items("Salmão fumado", "Smoked Salmon"));
        itemsRepository.save(new Items("Barra de Marte", "Mars Bar"));
        itemsRepository.save(new Items("Bolinhos de Arroz", "Rice Krispies"));
        itemsRepository.save(new Items("pimenta ancho", "Ancho Chillies"));
        itemsRepository.save(new Items("Leite de amêndoa", "Almond Milk"));
        itemsRepository.save(new Items("Pimenta da Jamaica", "Allspice"));
        itemsRepository.save(new Items("Extrato de amêndoa", "Almond Extract"));
        itemsRepository.save(new Items("Dobrada", "Tripe"));
        itemsRepository.save(new Items("Carne de cabra", "Goat Meat"));
        itemsRepository.save(new Items("Feijões pretos", "Black Beans"));
        itemsRepository.save(new Items("filé de anchova", "Anchovy Fillet"));
        itemsRepository.save(new Items("Ras el hanout", "Ras el hanout"));
        itemsRepository.save(new Items("massa folhada", "Filo Pastry"));
        itemsRepository.save(new Items("Água de flor de laranja", "Orange Blossom Water"));
        itemsRepository.save(new Items("casca cristalizada", "Candied Peel"));
        itemsRepository.save(new Items("Grand Marnier", "Grand Marnier"));
        itemsRepository.save(new Items("Xerez", "Sherry"));
        itemsRepository.save(new Items("Água de rosas", "Rose water"));
        itemsRepository.save(new Items("Tempero misto", "Mixed Spice"));
        itemsRepository.save(new Items("Carne moída", "Mincemeat"));
        itemsRepository.save(new Items("Batatas doces", "Sweet Potatoes"));
        itemsRepository.save(new Items("Pães", "Bread Rolls"));
        itemsRepository.save(new Items("pão", "Bun"));
        itemsRepository.save(new Items("Pão de Batata", "Potatoe Buns"));
        itemsRepository.save(new Items("Carne de porco moída", "Ground Pork"));
        itemsRepository.save(new Items("Costeletas de porco", "Pork Chops"));
        itemsRepository.save(new Items("Batatas Douradas Yukon", "Yukon Gold Potatoes"));
        itemsRepository.save(new Items("Cebola amarela", "Yellow Onion"));
        itemsRepository.save(new Items("Concentrado de caldo de carne", "Beef Stock Concentrate"));
        itemsRepository.save(new Items("Concentrado de Caldo de Frango", "Chicken Stock Concentrate"));
        itemsRepository.save(new Items("pepino persa", "Persian Cucumber"));
        itemsRepository.save(new Items("Maionese", "Mayonnaise"));
        itemsRepository.save(new Items("Sriracha", "Sriracha"));
        itemsRepository.save(new Items("Ruibarbo", "Rhubarb"));
        itemsRepository.save(new Items("Pão Pita", "Pita Bread"));
        itemsRepository.save(new Items("Trigo Bulgur", "Bulgur Wheat"));
        itemsRepository.save(new Items("Quinoa", "Quinoa"));
        itemsRepository.save(new Items("picles de endro", "Dill Pickles"));
        itemsRepository.save(new Items("Pãezinhos De Hambúrguer De Semente De Sésamo", "Sesame Seed Burger Buns"));
        itemsRepository.save(new Items("pãezinhos", "Buns"));
        itemsRepository.save(new Items("Alface Iceberg", "Iceberg Lettuce"));
        itemsRepository.save(new Items("molho de pepino", "Gherkin Relish"));
        itemsRepository.save(new Items("fatias de queijo", "Cheese Slices"));
        itemsRepository.save(new Items("Encurtando", "Shortening"));
        itemsRepository.save(new Items("Água morna", "Warm Water"));
        itemsRepository.save(new Items("Água fervente", "Boiling Water"));
        itemsRepository.save(new Items("Suco de picles", "Pickle Juice"));
        itemsRepository.save(new Items("Açúcar em pó", "Powdered Sugar"));
        itemsRepository.save(new Items("Kielbasa", "Kielbasa"));
        itemsRepository.save(new Items("Sausage polonês", "Polish Sausage"));
        itemsRepository.save(new Items("Chucrute", "Sauerkraut"));
        itemsRepository.save(new Items("Semente de alcaravia", "Caraway Seed"));
        itemsRepository.save(new Items("arenque", "Herring"));
        itemsRepository.save(new Items("Geléia", "Jam"));
        itemsRepository.save(new Items("Mulukhiyah", "Mulukhiyah"));
        itemsRepository.save(new Items("arroz de sushi", "Sushi Rice"));
        itemsRepository.save(new Items("figos", "Figs"));
        itemsRepository.save(new Items("Cidra", "Cider"));
        itemsRepository.save(new Items("Beterraba", "Beetroot"));
        itemsRepository.save(new Items("sardinha", "Sardines"));
        itemsRepository.save(new Items("ciabatta", "Ciabatta"));
        itemsRepository.save(new Items("trigo sarraceno", "Buckwheat"));
    }
}
